alter table public.videos
    add column if not exists generation_status text default 'generated',
    add column if not exists publish_status text,
    add column if not exists is_series boolean default false,
    add column if not exists series_group_id text,
    add column if not exists series_title text,
    add column if not exists part_number integer,
    add column if not exists part_count integer,
    add column if not exists publish_after timestamptz,
    add column if not exists source_fingerprint text,
    add column if not exists story_type text,
    add column if not exists source_region text,
    add column if not exists scene_count integer,
    add column if not exists ending_type text,
    add column if not exists trigger_source text;

update public.videos
set
    publish_status = coalesce(publish_status, 'ready'),
    generation_status = coalesce(generation_status, 'generated'),
    story_type = coalesce(story_type, nullif(research_brief ->> 'story_type', '')),
    source_region = coalesce(source_region, nullif(research_brief ->> 'source_region', '')),
    is_series = coalesce(is_series, coalesce((research_brief ->> 'series_potential')::boolean, false)),
    part_number = coalesce(part_number, nullif(production_plan ->> 'series_part', '')::integer),
    part_count = coalesce(part_count, nullif(production_plan ->> 'series_total', '')::integer),
    scene_count = coalesce(
        scene_count,
        case
            when jsonb_typeof(production_plan -> 'scenes') = 'array' then jsonb_array_length(production_plan -> 'scenes')
            else null
        end
    )
where true;

alter table public.videos
    alter column publish_status set default 'ready';

create index if not exists idx_videos_publish_status on public.videos (publish_status);
create index if not exists idx_videos_generation_status on public.videos (generation_status);
create index if not exists idx_videos_series_group on public.videos (series_group_id, part_number);
create index if not exists idx_videos_source_fingerprint on public.videos (source_fingerprint);
create index if not exists idx_videos_publish_after on public.videos (publish_after);
create index if not exists idx_videos_story_type on public.videos (story_type);
create index if not exists idx_videos_source_region on public.videos (source_region);

comment on column public.videos.generation_status is 'generation lifecycle status: generating/generated/failed';
comment on column public.videos.publish_status is 'publication lifecycle status: ready/queued/uploading/uploaded/failed';
comment on column public.videos.series_group_id is 'logical group id shared across parts of one story series';
comment on column public.videos.series_title is 'shared series title for grouped parts';
comment on column public.videos.part_number is '1-based series part number';
comment on column public.videos.part_count is 'total part count for a series';
comment on column public.videos.publish_after is 'earliest intended publish time for queued content';
comment on column public.videos.source_fingerprint is 'dedupe fingerprint derived from source title/story';
comment on column public.videos.story_type is 'story_type from research_brief';
comment on column public.videos.source_region is 'source region from research_brief';
comment on column public.videos.scene_count is 'number of scenes in production_plan';
comment on column public.videos.ending_type is 'ending classification such as payoff or cliffhanger';
comment on column public.videos.trigger_source is 'manual, schedule, slot_check, queue';

alter table public.runs
    add column if not exists trigger_source text,
    add column if not exists retry_count integer default 0,
    add column if not exists failure_stage text,
    add column if not exists slot_key text,
    add column if not exists run_meta jsonb default '{}'::jsonb;

create index if not exists idx_runs_type_started_at on public.runs (run_type, started_at desc);
create index if not exists idx_runs_slot_key on public.runs (slot_key);

comment on column public.runs.run_type is 'research/generate/publish/collect_analytics/analyze_patterns';
comment on column public.runs.trigger_source is 'manual, schedule, slot_check, queue';
comment on column public.runs.retry_count is 'retry counter for automated jobs';
comment on column public.runs.failure_stage is 'pipeline stage that failed';
comment on column public.runs.slot_key is 'scheduler slot key tied to an automated run';
comment on column public.runs.run_meta is 'small structured metadata for a run';

comment on column public.videos.research_brief is 'research_brief JSON generated by researcher agent';
comment on column public.patterns.pattern_type is 'topic/style/story_type/emotion/source_region/series_format/ending_type/scene_density/avoid/recommendation';
